### ISSUE TITLE
ViewController - "Type 'String' has no member 'opus'?

### ISSUE THREAD

**Issue by leemet16** [watson-developer-cloud/simple-chat-swift#14]
I've followed the directions on the tutorial page, but cannot get this sample (or other watson iOS samples to compile). I consistently see "Type 'String' has no member 'opus' as the compile error.

In the case of this simple-chat-swift example, the compile error shows up in the ViewController on the following line:

var settings = RecognitionSettings(contentType: .opus)

Is there a new/additional configuration step needed to get this to compile?

**Comment by germanattanasio** [comment]
I think that after we switch to the generated SDK some of the parameters have changed.
I will try to get someone to look at it, but It will probably take some time. Do you think you can see the changes in https://github.com/watson-developer-cloud/swift-sdk/blob/master/CHANGELOG.md and update this sample?
I can help you with during the process for the PR.

**Comment by kaushikibm** [comment]
Hi All

we also faced this issue in our project, is there any solution to it.

**Comment by leemet16** [comment]
I was able to fix this in the sample. The underlying SDK did indeed change. The docs for the SDK show the proper invocation for this call (and there's a 2nd call within the same method "startTranscribing" that will then also need to be updated). I hope to have a pull request in the next week.  Check out the docs: http://watson-developer-cloud.github.io/swift-sdk/swift-api/services/AssistantV1/index.html#assistant and the section within titled "Transcribe Microphone Audio"

**Comment by germanattanasio** [comment]
@leemet16 do you think you can write a PR to fix this sample? That will be awesome!

**Comment by leemet16** [comment]
@germanattanasio PR written.

**Comment by germanattanasio** [comment]
Fixed by @leemet16

**Comment by kaushikibm** [comment]
after changing the code supporting the new framework facing issue with xcode 9.4.1. Getting the below issue 
error: The following binaries use incompatible versions of Swift:
/Users/******/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/WestfieldAppV2.app/Frameworks/SpeechToTextV1.framework/SpeechToTextV1
/Users/*******/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/WestfieldAppV2.app/WestfieldAppV2

**Comment by kaushikibm** [comment]
Hi Everyone

I am still facing issue in this, can somebody let me know the fix for this issue "Type 'String' has no member 'opus'"

**Comment by germanattanasio** [comment]
Let me see if I can find someone with time to help you here.

**Comment by AnthonyOliveri** [comment]
@kaushikibm Do you still get the same build errors after deleting the `DerivedData` folder?

I tried the Simple Chat app myself on Xcode 9.4.1, installing `swift-sdk` version 0.34.0 with Carthage. Once I added my Credentials, the app built successfully.

If deleting your DerivedData folder doesn't work, could you upload a .zip of your version of Simple Chat so we can debug it?

**Comment by kaushikibm** [comment]
Thanks Anthony for quick response.

I am not getting those errors now and am able to build successfully but when am my pushing my app to app store got the following errors.

Invalid Binary Architecture - iOS 3.0 introduced support for multiple binary architectures. If your binary is built for multiple architectures, your Info.plist must have a MinimumOSVersion key with a value of at least 3.0. Additionally, if your app is intended to support earlier iPhone and iPod touch models, your app must contain at least an armv6 binary; "thin" armv7-only binaries will not be accepted unless the armv7 required device capability is also present in the Info.plist UIRequiredDeviceCapabilities key or the MinimumOSVersion key has a value of 4.3 or higher.

Specifically, we found the following unsupported architectures in your binary:

    x86_64
    i386

For more information, see Technical Q&A QA1707 at: http://developer.apple.com/iphone/library/qa/qa2010/qa1707.html.

Invalid Mach-O Format - The Mach-O in bundle "XXXX.app/Frameworks/WebImage.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

Invalid Mach-O Format - The Mach-O in bundle "XXXX.app/Frameworks/RestKit.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

Invalid Mach-O Format - The Mach-O in bundle "XXXX.app/Frameworks/TTTAttributedLabel.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

Invalid Mach-O Format - The Mach-O in bundle "XXXX.app/Frameworks/TextToSpeechV1.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

Invalid Mach-O Format - The Mach-O in bundle "XXXX.app/Frameworks/SpeechToTextV1.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

Invalid Mach-O Format - The Mach-O in bundle "XXXX.app/Frameworks/Starscream.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

Invalid Segment Alignment - The app binary at 'XXXX.app/Frameworks/RestKit.framework/RestKit' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Segment Alignment - The app binary at 'XXXX.app/Frameworks/SpeechToTextV1.framework/SpeechToTextV1' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Segment Alignment - The app binary at 'XXXX.app/Frameworks/Starscream.framework/Starscream' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Segment Alignment - The app binary at 'XXXX.app/Frameworks/TTTAttributedLabel.framework/TTTAttributedLabel' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Segment Alignment - The app binary at 'XXXX.app/Frameworks/TextToSpeechV1.framework/TextToSpeechV1' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Segment Alignment - The app binary at 'XXXX.app/Frameworks/WebImage.framework/WebImage' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Encryption Info - The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

Though you are not required to fix the following issues, we wanted to make you aware of them:

Non-PIE Binary - The executable 'Payload/XXXX.app/Frameworks/RestKit.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Non-PIE Binary - The executable 'Payload/XXXX.app/Frameworks/SpeechToTextV1.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Non-PIE Binary - The executable 'Payload/XXXX.app/Frameworks/Starscream.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Non-PIE Binary - The executable 'Payload/XXXX.app/Frameworks/TextToSpeechV1.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Non-PIE Binary - The executable 'Payload/XXXX.app/Frameworks/TTTAttributedLabel.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Non-PIE Binary - The executable 'Payload/XXXX.app/Frameworks/WebImage.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable 

Can you please guide me how I can resolve these issues

**Comment by AnthonyOliveri** [comment]
WebImage and TTTAttributedLabel are not owned by IBM. Since you are seeing the same errors for those frameworks as you are for the Watson frameworks, this is likely an issue with how your app is building its dependencies.

I'm wondering if this is a result of Carthage using pre-built binaries (built for a different architecture for your app). Try deleting the `Carthage` folder and reinstall using `carthage update --platform iOS --no-use-binaries`. Make sure the Command Line Tools in Xcode's Preferences is set to the correct version of Xcode before running that command.

**Comment by kaushikibm** [comment]
Hi Anthony

Tried the steps you have mentioned , still got the mail from APP Store with the same errors . 
Need urgent help regarding this.

**Comment by AnthonyOliveri** [comment]
@kaushikibm Unfortunately, there's nothing more we can do to help, since this issue is not specific to the Simple Chat starter or the Watson services it uses.

I recommend contacting Apple's developer support.

**Comment by kaushikibm** [comment]
Hi Anthony

Can you please let me know the updated path to be used , am using the below path in carthage.
github "watson-developer-cloud/ios-sdk" , please share the pod path also  supporting Xcode 9.4.

Thanks
Kaushik

**Comment by AnthonyOliveri** [comment]
@kaushikibm You can find that information in the Swift SDK [README](https://github.com/watson-developer-cloud/swift-sdk#installation).
